package algonquin.cst2335.finalprojectandroid;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * File name: Recipe.java
 * Author: Tsaichun Chang
 * Course: CST2335-022
 * Assignment: Final Project
 * Date: 2024-03-29
 *
 * @author Tsaichun Chang
 * @version 1
 *
 * Entity class representing a recipe in the database.
 * This class is used by Room to create the recipes table, with fields representing the table columns.
 *
 * @Entity(tableName = "recipes") Defines the table name in the database.
 */
@Entity(tableName = "recipes")
public class Recipe {

    /**
     * Unique ID for the recipe, auto-generated by the database.
     * This is the primary key of the recipes table.
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name="id")
    public int id;

    /**
     * External recipe ID, as specified by the recipe source API.
     */
    @ColumnInfo(name = "recipe_id")
    public int recipeId;

    /**
     * Title of the recipe.
     */
    @ColumnInfo(name = "title")
    public String title;

    /**
     * URL to the image of the recipe.
     */
    @ColumnInfo(name = "image")
    public String image;

    /**
     * Summary or description of the recipe.
     */
    @ColumnInfo(name = "summary")
    public String summary;

    /**
     * URL to the source of the recipe.
     */
    @ColumnInfo(name = "sourceUrl")
    public String sourceUrl;

    /**
     * Default constructor required by Room for instantiation.
     */
    public Recipe() {

    }

    /**
     * Constructor for creating a Recipe object with all fields except the database primary key.
     *
     * @param r The recipe's ID from the source API.
     * @param t The title of the recipe.
     * @param i URL to the recipe's image.
     * @param s Summary or description of the recipe.
     * @param u URL to the source of the recipe.
     */
    public Recipe(int r, String t, String i, String s, String u) {
        recipeId = r;
        title = t;
        image = i;
        summary = s;
        sourceUrl = u;
    }

    /**
     * Constructor for creating a Recipe object with a subset of fields: ID, title, and image URL.
     *
     * @param r The recipe's ID from the source API.
     * @param t The title of the recipe.
     * @param i URL to the recipe's image.
     */
    public Recipe(int r, String t, String i) {
        recipeId = r;
        title = t;
        image = i;
    }

    /**
     * Constructor for creating a Recipe object with a subset of fields: image URL, summary, and source URL.
     *
     * @param i URL to the recipe's image.
     * @param s Summary or description of the recipe.
     * @param u URL to the source of the recipe.
     */
    public Recipe(String i, String s, String u) {
        image = i;
        summary = s;
        sourceUrl = u;
    }

    public int getRecipeId(){return recipeId;}
    public String getTitle(){return title;}
    public String getImage(){return image;}
    public String getSummary(){return summary;}
    public String getSourceUrl(){return sourceUrl;}

}
